from setuptools import setup

setup(name='mnutils',
      version='0.1',
      description='Handy utilities and sklearn-style vectorizers for TEXTY.org.ua research of manipulative news. Works on Python 3.6 only (f-strings are everywhere)',
      url='http://github.com/texty',
      author='Nadiia Romanenko',
      author_email='nadiiaromanenko@gmail.com',
      license='MIT',
      packages=['mnutils'],
      install_requires=[
          'pandas',
          'numpy',
          'polyglot',
          'gensim',
          'scikit-learn',
          'pymorphy2',
          'pymorphy2-dicts-uk',
          'sqlalchemy',
          'psycopg2',
          'tqdm',
          'beautifulsoup4',
          'requests',
      ],
      zip_safe=False)